'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowDownToLine, ArrowUpRight, BarChart3, CalendarDays, Check, ChevronRight, CircleHelp, ClipboardCheck, FileText, Globe2, Layers3, LayoutDashboard, Radio, RefreshCw, Search, Settings2, ShieldCheck, X, Zap } from 'lucide-react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
type Row={id:string;fields:Record<string,any>};
type Data={state:string;accounts:Row[];posts:Row[];history:Row[];activity:Row[];fetchedAt?:string;errors?:Record<string,string>;truncated?:string[]};
const empty:Data={state:'loading',accounts:[],posts:[],history:[],activity:[]};
const base='https://airtable.com/app72eKOnd9oaiCyR';
const nav=[['Overview',LayoutDashboard],['Content library',Layers3],['Approval queue',ClipboardCheck],['Publishing calendar',CalendarDays],['Performance',BarChart3],['Accounts',Globe2],['Activity',Activity],['Setup',Settings2]] as const;
const descriptions:Record<string,string>={Overview:'A clear view of your content, from first draft to lasting impact.','Content library':'Every destination. Every format. One organized workspace.','Approval queue':'Review the content waiting for a publishing decision.','Publishing calendar':'See what is scheduled and what has already gone live.',Performance:'Understand the performance of your published content.',Accounts:'Manage publication mappings and monitor account readiness.',Activity:'Follow publishing attempts, refreshes and recovery events.',Setup:'The foundation is built. Connect the remaining services.'};
function text(v:any){return typeof v==='string'?v:Array.isArray(v)?v.join(', '):v==null?'':String(v)}
function date(v:any){return v?new Date(v).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'}):'—'}
function number(v:any){return typeof v==='number'?v.toLocaleString('en-GB'):'—'}
function Metric({post,field}:{post:Row;field:string}){let metadata:any={};try{metadata=JSON.parse(post.fields['Metric Metadata']||'{}')}catch{}const map:Record<string,string>={'IG Views':'views','IG Reach':'reach','IG Likes':'likes','IG Comments':'comments','IG Shares':'shares','IG Saves':'saved'};const state=metadata.metrics?.[map[field]]?.state;const retained=typeof post.fields[field]==='number'&&state&&state!=='available';return <><span>{number(post.fields[field])}</span>{retained&&<small title="The latest request did not return this metric; this is its previous available value.">Last available</small>}</>}
function Badge({value}:{value:any}){const s=text(value)||'Not set';return <span className={'badge '+(/Published|Current|Connected|Approved|Succeeded/.test(s)?'good':/Failed|Reauthorization/.test(s)?'bad':/Pending|Review|Partial|Reconciliation/.test(s)?'warn':'')}>{s}</span>}
function Empty({title,body}:{title:string;body:string}){return <div className="empty"><div className="empty-icon"><Layers3 size={28}/></div><h3>{title}</h3><p>{body}</p></div>}
export default function Workspace(){
 const refreshing=useRef(false);
 const [page,setPage]=useState('Overview'),[data,setData]=useState<Data>(empty),[busy,setBusy]=useState(false),[error,setError]=useState(''),[stale,setStale]=useState(false),[search,setSearch]=useState(''),[account,setAccount]=useState('all'),[format,setFormat]=useState('all'),[promotion,setPromotion]=useState('all'),[selected,setSelected]=useState<Row|null>(null),[sort,setSort]=useState('newest'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[month,setMonth]=useState(new Date().toISOString().slice(0,7));
 async function refresh(){if(refreshing.current)return;refreshing.current=true;setBusy(true);setError('');try{const r=await fetch('/api/workspace',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:'{}'});const d=await r.json() as Data & {error?:string};if(!r.ok)throw new Error(d.error||'Could not refresh the workspace');setData(previous=>{const merged={...d}; for(const key of Object.keys(d.errors||{})){if(["accounts","posts","history","activity"].includes(key)){const k=key as "accounts"|"posts"|"history"|"activity";merged[k]=previous[k];}}return merged});setStale(Object.keys(d.errors||{}).length>0);}catch(e){setError(e instanceof Error?e.message:'Refresh failed');setStale(true);setData(d=>d.state==='loading'?{...d,state:'error'}:d)}finally{refreshing.current=false;setBusy(false)}}
 useEffect(()=>{refresh();const timer=window.setInterval(()=>{if(document.visibilityState==='visible'&&!refreshing.current)refresh()},120000);return()=>window.clearInterval(timer)},[]);
 const ready=data.state==='connected', accountNames=Object.fromEntries(data.accounts.map(a=>[a.id,a.fields['Publication']||a.fields['Account Name']]));
 const posts=useMemo(()=>data.posts.filter(p=>p.fields['Post Title']||p.fields['Instagram Media ID']).filter(p=>{const f=p.fields,when=f['Published At']||f['Scheduled At'];return(account==='all'||f.Account?.includes(account))&&(format==='all'||f['Media Format']===format)&&(promotion==='all'||f['Promotion Status']===promotion)&&(!search||`${f['Post Title']} ${f.Caption}`.toLowerCase().includes(search.toLowerCase()))&&(!from||(when&&when>=from))&&(!to||(when&&when.slice(0,10)<=to))}).sort((a,b)=>sort==='views'?(b.fields['IG Views']??-1)-(a.fields['IG Views']??-1):String(b.fields['Published At']||b.fields['Scheduled At']||'').localeCompare(String(a.fields['Published At']||a.fields['Scheduled At']||''))),[data.posts,account,format,promotion,search,sort,from,to]);
 const published=posts.filter(p=>p.fields['Publishing Status']==='Published'),approval=posts.filter(p=>p.fields['Content Status']==='In Review');
 const sum=(metric:string)=>{const values=published.map(p=>p.fields[metric]).filter(v=>typeof v==='number');return values.length?values.reduce((a,b)=>a+b,0):undefined};
 function download(){const columns=['Post Title','Media Format','Publishing Status','Instagram Media ID','Published At','IG Views','IG Reach','IG Likes','IG Comments','IG Shares','IG Saves','Promotion Status','Last Insights Success'];const csv=[columns,...posts.map(p=>columns.map(c=>text(p.fields[c])))].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mo4-content-export.csv';a.click();URL.revokeObjectURL(url)}
 const filters=<div className="filters"><label className="search"><Search size={16}/><input aria-label="Search content" placeholder="Search content..." value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Publication" value={account} onChange={e=>setAccount(e.target.value)}><option value="all">All publications</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{accountNames[a.id]}</option>)}</select><select aria-label="Format" value={format} onChange={e=>setFormat(e.target.value)}><option value="all">All formats</option>{['Image','Carousel','Reel','Story','Video','Live'].map(f=><option key={f}>{f}</option>)}</select><select aria-label="Promotion" value={promotion} onChange={e=>setPromotion(e.target.value)}><option value="all">All promotion states</option>{['Unknown','Not promoted','Boosted','Ad-linked'].map(f=><option key={f}>{f}</option>)}</select><input type="date" aria-label="Published or scheduled from" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" aria-label="Published or scheduled to" value={to} onChange={e=>setTo(e.target.value)}/></div>;
 function table(rows:Row[]){return rows.length?<div className="table-wrap"><table><thead><tr><th>Content</th><th>Publication</th><th>Publishing</th><th>Views</th><th>Reach</th><th>Insights</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><button className="post-title" onClick={()=>setSelected(p)}>{p.fields['Post Title']||'Untitled post'}</button><small>{p.fields['Media Format']||'Format not set'} · {date(p.fields['Published At']||p.fields['Scheduled At'])}</small></td><td>{accountNames[p.fields.Account?.[0]]||'Unassigned'}</td><td><Badge value={p.fields['Publishing Status']}/></td><td><Metric post={p} field="IG Views"/></td><td><Metric post={p} field="IG Reach"/></td><td><Badge value={p.fields['Insights Status']}/></td></tr>)}</tbody></table></div>:<Empty title={ready?'No matching content yet':'Your content will appear here'} body={ready?'Add a draft in Airtable or connect discovery to import published media.':'Connect the secure data source to browse drafts, publishing jobs and real performance.'}/>}
 return <div className="app"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('Overview')}}><span>MO<span className="four">4</span></span><i>CONTENT HUB</i></a><div className="workspace-label">NETWORK WORKSPACE</div><nav>{nav.map(([name,Icon])=><button key={name} className={page===name?'active':''} onClick={()=>setPage(name)}><Icon size={18}/>{name}{name==='Approval queue'&&approval.length>0&&<b>{approval.length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="automation"><span className="dot"/>Automation not connected</div><p>Publishing follows approval.<br/>Performance follows publishing.</p><a href={base} target="_blank" rel="noreferrer">Open Airtable <ArrowUpRight size={14}/></a></div></aside>
 <main><header className="topbar"><div><span>Workspace</span><ChevronRight size={14}/><b>{page}</b></div><div className="top-actions"><span className="private"><ShieldCheck size={14}/>Private workspace</span><span className="avatar">YE</span></div></header><div className="content"><div className="heading"><div><div className="eyebrow">MO4 NETWORK / INSTAGRAM</div><h1>{page==='Overview'?'Content, in perspective.':page}</h1><p>{descriptions[page]}</p></div><button className="button" onClick={refresh} disabled={busy}><RefreshCw size={15} className={busy?'spin':''}/>{busy?'Refreshing':'Refresh data'}</button></div>
 {error&&<div className="notice error" role="alert">{error} {stale&&ready?'Previously loaded data is retained and may be stale.':''}</div>}
 {data.state==='setup_required'&&<div className="notice"><div className="notice-icon"><Zap size={20}/></div><div><b>Your workspace foundation is ready</b><p>Connect Airtable to bring in live content and performance. Seven n8n workers are built; credentials and live acceptance are still required.</p></div><button onClick={()=>setPage('Setup')}>View setup <ArrowUpRight size={15}/></button></div>}
 {data.truncated?.length? <div className="notice">Showing at most 500 records per source. Network totals are partial. Server-side pagination is needed for larger inventories.</div>:null}
 {Object.entries(data.errors||{}).map(([k,v])=><div className="notice error" key={k}>{k}: {v}. Refresh failed for this source. Any previously loaded rows are retained and stale.</div>)}
 {page==='Overview'&&<><div className="stat-grid">{[['Published posts',ready?published.length:undefined,'Within your selected content window'],['Instagram views',sum('IG Views'),'Available organic observations'],['Interactions',sum('IG Total Interactions'),'Reported total interactions only'],['Awaiting approval',ready?approval.length:undefined,'Ready for a review decision']].map(([label,value,note])=><div className="stat" key={String(label)}><label>{label}<ArrowUpRight size={16}/></label><strong>{number(value)}</strong><small>{note}</small></div>)}</div><div className="two-column"><section className="panel"><div className="panel-head"><div><h2>Publication pulse</h2><p>One network. Independent account health.</p></div><Globe2 size={18}/></div>{data.accounts.length?<div className="account-list">{data.accounts.map(a=><button key={a.id} onClick={()=>{setAccount(a.id);setPage('Content library')}}><span className="publication-mark">{text(a.fields.Publication).slice(0,2).toUpperCase()}</span><span><b>{a.fields.Publication}</b><small>{a.fields['Instagram Username']?'@'+a.fields['Instagram Username']:'Account mapping pending'}</small></span><Badge value={a.fields['Connection Status']}/><ChevronRight size={16}/></button>)}</div>:<Empty title="Your publications, together" body="Account mappings will load from Airtable after the data connection is configured."/>}</section><section className="panel journey"><div className="panel-head"><div><h2>The complete content cycle</h2><p>A deliberate route from idea to insight.</p></div><Radio size={18}/></div>{[['01','Prepare & review','Draft content and approve the exact version.'],['02','Schedule & publish','Route each post to its verified account.'],['03','Measure & learn','Keep latest metrics and timestamped history.']].map(([n,t,d])=><div className="journey-item" key={n}><span>{n}</span><div><b>{t}</b><p>{d}</p></div></div>)}<div className="quiet-note"><ShieldCheck size={16}/>No posts are published from this dashboard yet.</div></section></div><section className="panel"><div className="panel-head"><div><h2>Recent content</h2><p>Latest published and scheduled posts</p></div><button className="text-button" onClick={()=>setPage('Content library')}>View library <ArrowUpRight size={15}/></button></div>{table(posts.slice(0,5))}</section></>}
 {['Content library','Approval queue','Performance'].includes(page)&&<><div className="toolbar">{filters}<div className="table-actions"><select aria-label="Sort content" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="views">Most views</option></select><button className="button" onClick={download} disabled={!ready||!posts.length}><ArrowDownToLine size={15}/>Export CSV</button><a className="button orange" href={base+'/tblSDEJXTXmMhiuxw'} target="_blank" rel="noreferrer"><FileText size={15}/>Manage in Airtable</a></div></div>{page==='Performance'&&<div className="metric-note"><CircleHelp size={16}/>These are latest cumulative observations, not daily increments. Reach is shown per post; it is not added into a unique network total.</div>}{page==='Approval queue'&&<div className="metric-note"><ClipboardCheck size={16}/>Review is managed in Airtable during setup. Approve the exact account, caption, media and schedule in Airtable. Any change requires reapproval.</div>}<section className="panel">{table(page==='Approval queue'?approval:page==='Performance'?published:posts)}</section></>}
 {page==='Publishing calendar'&&<><div className="calendar-tools"><label>Month <input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><a className="button" href={base+'/tblSDEJXTXmMhiuxw'} target="_blank" rel="noreferrer">Manage schedule <ArrowUpRight size={15}/></a></div><section className="panel">{ready?<div className="calendar-grid">{Array.from({length:new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate()},(_,i)=>{const day=month+'-'+String(i+1).padStart(2,'0');const rows=posts.filter(p=>(p.fields['Scheduled At']||p.fields['Published At']||'').startsWith(day));return <div className="calendar-day" key={day}><b>{i+1}</b>{rows.map(p=><button key={p.id} onClick={()=>setSelected(p)}>{p.fields['Post Title']||'Untitled'}<small>{accountNames[p.fields.Account?.[0]]}</small></button>)}</div>})}</div>:<Empty title="A calmer publishing calendar" body="Scheduled posts will appear here when the Airtable data connection is ready."/>}</section></>}
 {page==='Accounts'&&<><div className="metric-note"><ShieldCheck size={16}/>Popeye is the publishing test account. MO4 mappings are pending verification; onboarding does not enable publishing.</div><div className="accounts-grid">{data.accounts.map(a=><section className="panel account-card" key={a.id}><div className="panel-head"><span className="publication-mark">{text(a.fields.Publication).slice(0,2).toUpperCase()}</span><Badge value={a.fields['Connection Status']}/></div><h2>{a.fields.Publication}</h2><p>{a.fields['Instagram Username']?'@'+a.fields['Instagram Username']:'Instagram account not mapped'}</p><dl><dt>Publishing</dt><dd>{a.fields['Publishing Enabled']?'Enabled':'Disabled'}</dd><dt>Insights</dt><dd>{a.fields['Insights Enabled']?'Enabled':'Disabled'}</dd><dt>Timezone</dt><dd>{a.fields.Timezone||'Not set'}</dd><dt>Last success</dt><dd>{date(a.fields['Last Successful Sync'])}</dd></dl><a className="text-button" href={base+'/tblInBXmP2Hj0At0B/'+a.id} target="_blank" rel="noreferrer">Review account <ArrowUpRight size={15}/></a></section>)}</div>{!data.accounts.length&&<section className="panel"><Empty title="Account readiness at a glance" body="Connect Airtable to review account mappings, publication labels and collection health."/></section>}</>}
 {page==='Activity'&&<section className="panel"><div className="panel-head"><div><h2>Workspace activity</h2><p>Persistent outcomes from your automations</p></div><Activity size={18}/></div>{data.activity.length?<div className="activity-list">{[...data.activity].sort((a,b)=>text(b.fields['Started At']).localeCompare(text(a.fields['Started At']))).map(r=><div key={r.id}><span className="activity-icon"><Activity size={16}/></span><div><b>{r.fields.Operation||'Event'}</b><p>{r.fields.Summary}</p><small>{date(r.fields['Started At'])}</small></div><Badge value={r.fields.Outcome}/></div>)}</div>:<Empty title="Nothing runs silently" body="Publishing attempts, insight refreshes and recoveries will be logged here once automation is connected."/>}</section>}
 {page==='Setup'&&<div className="two-column"><section className="panel setup"><div className="panel-head"><div><h2>Launch checklist</h2><p>Clear progress, without premature activation.</p></div><ShieldCheck size={18}/></div>{[['Four-table Airtable foundation','Complete','Accounts, Content & Posts, Insight History and Activity Log are created.'],['Five Airtable safeguards','Built','Draft setup, approvals, reapproval, post identity and daily health are saved as off drafts.'],['Account inventory','In progress','Popeye and three MO4 publication placeholders are present. IDs and access need verification.'],['Dashboard data connection',ready?'Connected':'Required','A secure read-only connection is required before live records can appear.'],['n8n workflow implementation','Built','Seven workflows are created. Secure credential binding and live acceptance remain.'],['End-to-end acceptance','Pending','Publish one approved test post, collect its metrics and verify history.']].map(([t,s,d])=><div className="checklist" key={t}><span className={s==='Complete'?'completed':''}>{s==='Complete'?<Check size={16}/>:<ChevronRight size={16}/>}</span><div><b>{t}</b><p>{d}</p></div><Badge value={s}/></div>)}</section><section className="panel setup"><h2>A compact foundation</h2><p>One account destination per post. Four linked tables. Every measurement has a source and timestamp.</p><div className="schema-list">{[['Accounts','Publication identity and connection health'],['Content & Posts','Drafts, approval, publishing, metrics and promotions'],['Insight History','Cumulative observations over time'],['Activity Log','Attempts, outcomes and recovery']].map(([t,d])=><div key={t}><Layers3 size={18}/><span><b>{t}</b><small>{d}</small></span></div>)}</div><a className="button orange" href={base} target="_blank" rel="noreferrer">Open the working base <ArrowUpRight size={15}/></a><p className="fine">No live publishing or performance collection is enabled. This dashboard currently provides read-only exploration; write actions follow after the approved publishing flow is integrated.</p></section></div>}
 <footer><span>MO4 Content Hub <span className="footer-dot">·</span> From publishing to perspective.</span><span>{data.fetchedAt?'Last read '+date(data.fetchedAt)+' · Refreshes every 2 minutes':'Awaiting secure data connection'}</span></footer></div></main>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal" role="dialog" aria-modal="true" aria-label="Post details" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close post details" onClick={()=>setSelected(null)}><X size={20}/></button><div className="eyebrow">POST DETAIL</div><h2>{selected.fields['Post Title']||'Untitled post'}</h2><div className="modal-badges"><Badge value={selected.fields['Publishing Status']}/><Badge value={selected.fields['Insights Status']}/><Badge value={selected.fields['Promotion Status']}/></div><p className="caption">{selected.fields.Caption||'No caption stored.'}</p><div className="detail-metrics">{['IG Views','IG Reach','IG Likes','IG Comments','IG Shares','IG Saves','Combined Likes','Combined Comments','Combined Views'].map(k=><div key={k}><small>{k.replace('IG ','')}</small><strong><Metric post={selected} field={k}/></strong></div>)}</div><h3>Performance history</h3><History history={data.history.filter(h=>h.fields.Post?.includes(selected.id))}/><div className="metric-note">Observations are cumulative. Blank values mean unavailable, not zero. Last successful collection: {date(selected.fields['Last Insights Success'])}.</div><details><summary>Additional performance metrics</summary><pre>{selected.fields['Additional Insights']||'No additional metrics have been returned yet.'}</pre></details><details><summary>Metric availability and definitions</summary><pre>{selected.fields['Metric Metadata']||'No collection metadata recorded yet.'}</pre></details><details><summary>Promotion details</summary><pre>{selected.fields['Promotion Metadata']||'No promotion metadata recorded.'}</pre></details><div className="modal-links"><a className="button" href={base+'/tblSDEJXTXmMhiuxw/'+selected.id} target="_blank" rel="noreferrer">Open record <ArrowUpRight size={15}/></a>{/^https:\/\/([\w-]+\.)?instagram\.com\//i.test(selected.fields['Instagram Permalink']||'')&&<a className="button orange" href={selected.fields['Instagram Permalink']} target="_blank" rel="noreferrer">View Instagram post <ArrowUpRight size={15}/></a>}</div></section></div>}
 </div>
}
function History({history}:{history:Row[]}){const points=history.map(h=>({time:new Date(h.fields['Collected At']).getTime(),views:h.fields['IG Views']??null,reach:h.fields['IG Reach']??null})).filter(h=>Number.isFinite(h.time)).sort((a,b)=>a.time-b.time);return points.length?<div style={{height:230,width:'100%'}}><ResponsiveContainer><LineChart data={points}><CartesianGrid strokeDasharray="3 3" stroke="#e9e7e0"/><XAxis dataKey="time" tickFormatter={v=>new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}/><YAxis/><Tooltip labelFormatter={v=>date(v)}/><Line type="linear" dataKey="views" name="Instagram views" stroke="#ef683f" strokeWidth={2} connectNulls={false}/><Line type="linear" dataKey="reach" name="Post reach" stroke="#375f52" strokeWidth={2} connectNulls={false}/></LineChart></ResponsiveContainer></div>:<Empty title="History starts with the first observation" body="Snapshots will appear once the insight collector runs. Earlier observations are never reconstructed."/>}
